# Generated by Django 5.0.6 on 2024-06-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paciente", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="civilStatus",
            new_name="civil_status",
        ),
        migrations.RenameField(
            model_name="paciente",
            old_name="lasName",
            new_name="last_name",
        ),
        migrations.AlterField(
            model_name="paciente",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="document",
            field=models.PositiveBigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
