# Generated by Django 5.0.6 on 2024-06-20 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("paciente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=None)),
                ("reason", models.TextField()),
                ("treatment", models.TextField()),
                ("examsData", models.JSONField(default=dict)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paciente.paciente",
                    ),
                ),
            ],
        ),
    ]
